version: '3.8'
services:
  # Backend API
  backend:
    container_name: rbac-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    networks:
      - rbac-network

  frontend:
    container_name: rbac-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - rbac-network

networks:
  rbac-network:
    driver: bridge
