package middlewares

const (
	// Event
	EVENT_TYPE_CREATE_ACCESS = "EVENT_TYPE_CREATE"
	EVENT_TYPE_UPDATE_ACCESS = "EVENT_TYPE_UPDATE"
	EVENT_TYPE_DELETE_ACCESS = "EVENT_TYPE_DELETE"
	EVENT_TYPE_VIEW_ACCESS   = "EVENT_TYPE_VIEW"

	// Event
	EVENT_CREATE_ACCESS = "EVENT_CREATE"
	EVENT_UPDATE_ACCESS = "EVENT_UPDATE"
	EVENT_DELETE_ACCESS = "EVENT_DELETE"
	EVENT_VIEW_ACCESS   = "EVENT_VIEW"

	//Participants
	PARTICIPANTS_CREATE_ACCESS = "PARTICIPANTS_CREATE"
	PARTICIPANTS_UPDATE_ACCESS = "PARTICIPANTS_UPDATE"
	PARTICIPANTS_DELETE_ACCESS = "PARTICIPANTS_DELETE"
	PARTICIPANTS_VIEW_ACCESS   = "PARTICIPANTS_VIEW"

	// Users
	USER_CREATE_ACCESS = "USER_CREATE"
	USER_UPDATE_ACCESS = "USER_UPDATE"
	USER_DELETE_ACCESS = "USER_DELETE"
	USER_VIEW_ACCESS   = "USER_VIEW"

	// Role
	ROLE_CREATE_ACCESS = "ROLE_CREATE"
	ROLE_UPDATE_ACCESS = "ROLE_UPDATE"
	ROLE_DELETE_ACCESS = "ROLE_DELETE"
	ROLE_VIEW_ACCESS   = "ROLE_VIEW"
	ROLE_ASSIGN_ACCESS = "ROLE_ASSIGN"

	// Permission
	PERMISSION_CREATE_ACCESS = "PERMISSION_CREATE"
	PERMISSION_UPDATE_ACCESS = "PERMISSION_UPDATE"
	PERMISSION_DELETE_ACCESS = "PERMISSION_DELETE"
	PERMISSION_VIEW_ACCESS   = "PERMISSION_VIEW"
	PERMISSION_ASSIGN_ACCESS = "PERMISSION_ASSIGN"
)
